# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20171108_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_details',
            name='email_original',
        ),
        migrations.AlterField(
            model_name='search_details',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
