# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170616_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
