# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_box_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='box',
        ),
        migrations.DeleteModel(
            name='Box',
        ),
    ]
