# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20170619_0555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProfilename',
        ),
    ]
