# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20170619_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
