# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20170620_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_upload', models.FileField(blank=True, null=True, upload_to='media/csv/')),
            ],
        ),
    ]
