# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0019_auto_20170918_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=3)),
                ('date_pulled', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email_original', models.EmailField(max_length=30)),
                ('company_url', models.CharField(max_length=30)),
                ('email_guess', models.CharField(max_length=30)),
                ('email_score', models.CharField(max_length=3)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
